services:
  backend:
    build:
      context: .
      # target: development
      dockerfile: Dockerfile.dev
    container_name: skinner_backend
    ports:
      - '8000:80'
    volumes:
      - .:/code
    depends_on:
      - postgresql_skinner
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 2G
  postgresql_skinner:
    image: postgres
    restart: always
    container_name: postgresql_skinner
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    # dentro del mismo pod, se usa la puerta del contenedor para conectar
    # por ejemplo, si fuera 5433:5432, aún se usa 5432 para conectar del backend!
    ports:
      - '5433:5432'
    deploy:
      resources:
        limits:
          memory: 2G
volumes:
  postgres: