
FROM python:3.11
WORKDIR /code
COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
COPY ./app /code/app
# Adicionar archivo de variables del entorno
COPY ./.env /code/app/.env

# app-dir is para encontrar el main:app dentro de app,
# y el host 0.0.0.0 es para que podamos usar localhost:8000
CMD ["uvicorn", "main:app", "--port", "80", "--reload", "--app-dir", "app", "--host", "0.0.0.0"]