services:
  backend:
    build:
      context: .
      # target: development
      dockerfile: Dockerfile.dev
    container_name: skinner_backend
    ports:
      - '8000:80'
    volumes:
      - .:/code
    depends_on:
      - postgresql_skinner
    env_file:
      - .env
  postgresql_skinner:
    image: postgres
    restart: always
    container_name: postgresql_skinner
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5433:5432'
volumes:
  postgres: