services:
  backend:
    build:
      context: .
      # target: development
      dockerfile: Dockerfile.dev
    container_name: skinner_backend
    ports:
      - '8000:80'
    volumes:
      - .:/code
    depends_on:
      - postgresql_skinner
    env_file:
      - .env
  postgresql_skinner:
    image: postgres
    restart: always
    container_name: postgresql_skinner
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    # dentro del mismo pod, se usa la puerta del contenedor para conectar
    # por ejemplo, si fuera 5433:5432, aún se usa 5432 para conectar del backend!
    ports:
      - '5433:5432'
  # El "Redis" que usamos es Valkey, que es codigo abierto y compatible con Redis.
  valkey_skinner:
    image: valkey/valkey:latest
    container_name: valkey_skinner
    ports:
      - '6379:6379'
    volumes:
      - valkey_data:/data
volumes:
  postgres:
  valkey_data: