"""Crear tabla profesiones

Revision ID: 19dacb03f330
Revises: ab91b29b844b
Create Date: 2025-05-09 17:32:28.211852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19dacb03f330'
down_revision: Union[str, None] = 'ab91b29b844b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profesiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profesiones', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profesiones_id'), 'profesiones', ['id'], unique=False)
    op.add_column('nivel_educativo', sa.Column('estudiante_universitario', sa.String(), nullable=False))
    op.add_column('nivel_educativo', sa.Column('recien_graduado', sa.String(), nullable=False))
    op.add_column('nivel_educativo', sa.Column('egresado', sa.String(), nullable=False))
    op.drop_column('nivel_educativo', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nivel_educativo', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('nivel_educativo', 'egresado')
    op.drop_column('nivel_educativo', 'recien_graduado')
    op.drop_column('nivel_educativo', 'estudiante_universitario')
    op.drop_index(op.f('ix_profesiones_id'), table_name='profesiones')
    op.drop_table('profesiones')
    # ### end Alembic commands ###
