"""iniciando la tabla de usos de  candidatos

Revision ID: 221230bbc845
Revises: e01c1b70a87c
Create Date: 2025-05-28 23:44:10.025572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '221230bbc845'
down_revision: Union[str, None] = 'e01c1b70a87c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uso_de_la_app',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=False),
    sa.Column('last_reset', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['candidatos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uso_de_la_app')
    # ### end Alembic commands ###
