"""user_id_not_null_final

Revision ID: 229a5466986c
Revises: df8de30473d4
Create Date: 2025-08-29 17:38:41.916209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '229a5466986c'
down_revision: Union[str, None] = 'df8de30473d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clientes_name', table_name='clientes')
    op.create_index(op.f('ix_clientes_name'), 'clientes', ['name'], unique=False)
    op.alter_column('tipos_de_trabajo', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tipos_de_trabajo', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tipos_de_trabajo', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tipos_de_trabajo', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_clientes_name'), table_name='clientes')
    op.create_index('ix_clientes_name', 'clientes', ['name'], unique=True)
    # ### end Alembic commands ###
