"""agregando deleted_at para analisis y tipos de trabajo

Revision ID: 34b3c76a8d3e
Revises: a1b2c3d4e5f7
Create Date: 2026-02-16 21:36:55.973775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34b3c76a8d3e'
down_revision: Union[str, None] = 'a1b2c3d4e5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analisis', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('tipos_de_trabajo', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tipos_de_trabajo', 'deleted_at')
    op.drop_column('analisis', 'deleted_at')
    # ### end Alembic commands ###
