"""creando tablas planes de pago

Revision ID: 47d7347c4724
Revises: a1b2c3d4e5f7
Create Date: 2026-03-29 23:59:49.814562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47d7347c4724'
down_revision: Union[str, None] = 'a1b2c3d4e5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.Enum('FREE', 'MONTHLY', 'QUARTERLY', 'BIANNUAL', 'PREMIUM', 'FULL_ACCESS', name='planslug'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('analyses_limit', sa.Integer(), nullable=True),
    sa.Column('reports_limit', sa.Integer(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('suscripciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'EXPIRED', 'CANCELLED', name='subscriptionstatus'), nullable=False),
    sa.Column('analyses_used', sa.Integer(), nullable=False),
    sa.Column('reports_used', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('activated_by', sa.Integer(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activated_by'], ['usuario.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clientes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plan_id'], ['planes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_suscripciones_client_id', 'suscripciones', ['client_id'], unique=False)
    op.create_index('ix_suscripciones_expires_at', 'suscripciones', ['expires_at'], unique=False)
    op.create_index('ix_suscripciones_status', 'suscripciones', ['status'], unique=False)
    op.create_table('topups_analisis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('analysis_added', sa.Integer(), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'EXPIRED', 'CANCELLED', name='subscriptionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['suscripciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('analisis', 'deleted_at')
    op.add_column('clientes', sa.Column('contact_email', sa.String(), nullable=True))
    op.add_column('clientes', sa.Column('contact_phone', sa.String(), nullable=True))
    op.drop_column('tipos_de_trabajo', 'deleted_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tipos_de_trabajo', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('clientes', 'contact_phone')
    op.drop_column('clientes', 'contact_email')
    op.add_column('analisis', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_table('topups_analisis')
    op.drop_index('ix_suscripciones_status', table_name='suscripciones')
    op.drop_index('ix_suscripciones_expires_at', table_name='suscripciones')
    op.drop_index('ix_suscripciones_client_id', table_name='suscripciones')
    op.drop_table('suscripciones')
    op.drop_table('planes')
    # ### end Alembic commands ###
