"""agregaando campo created_at a la base de datos

Revision ID: 55d7c6a26665
Revises: 221230bbc845
Create Date: 2025-06-04 17:43:11.702134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55d7c6a26665'
down_revision: Union[str, None] = '221230bbc845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analisis', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analisis', 'created_at')
    # ### end Alembic commands ###
