"""agregando columna external_organization_id

Revision ID: 5ed413ef7740
Revises: 705c59c9fa83
Create Date: 2025-08-31 23:53:26.163180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ed413ef7740'
down_revision: Union[str, None] = '705c59c9fa83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('external_organization_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'clientes', ['external_organization_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clientes', type_='unique')
    op.drop_column('clientes', 'external_organization_id')
    # ### end Alembic commands ###
