"""borrando user_id en clientes y agreagando restrict

Revision ID: 705c59c9fa83
Revises: 229a5466986c
Create Date: 2025-08-29 22:56:44.150567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '705c59c9fa83'
down_revision: Union[str, None] = '229a5466986c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clientes_user_id', table_name='clientes')
    op.drop_column('clientes', 'user_id')
    op.drop_constraint('usuario_client_id_fkey', 'usuario', type_='foreignkey')
    op.create_foreign_key(None, 'usuario', 'clientes', ['client_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', type_='foreignkey')
    op.create_foreign_key('usuario_client_id_fkey', 'usuario', 'clientes', ['client_id'], ['id'], ondelete='CASCADE')
    op.add_column('clientes', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_clientes_user_id', 'clientes', ['user_id'], unique=False)
    # ### end Alembic commands ###
