"""issue-44

Revision ID: 75f324d14069
Revises: ab91b29b844b
Create Date: 2025-05-08 20:34:45.730223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75f324d14069'
down_revision: Union[str, None] = 'ab91b29b844b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidatos', sa.Column('firstname', sa.String(), nullable=False))
    op.add_column('candidatos', sa.Column('lastname', sa.String(), nullable=False))
    op.alter_column('candidatos', 'birthday',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=False,
               postgresql_using="birthday::date")
    op.drop_column('candidatos', 'name')
    op.alter_column('habilidades', 'name',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('perfil_del_trabajador', 'name',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('perfil_del_trabajador', 'name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('habilidades', 'name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.add_column('candidatos', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('candidatos', 'birthday',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('candidatos', 'lastname')
    op.drop_column('candidatos', 'firstname')
    # ### end Alembic commands ###
