"""agregar_client_id_a_analisis

Revision ID: b957f08eea0d
Revises: e691149bc285
Create Date: 2026-01-12 21:02:09.840716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b957f08eea0d'
down_revision: Union[str, None] = 'e691149bc285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Borrar registros existentes que no tienen client_id
    op.execute('DELETE FROM analisis')
    op.add_column('analisis', sa.Column('client_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'analisis', 'clientes', ['client_id'], ['id'], ondelete='CASCADE')
    # Solo borrar si la columna existe (puede no existir en algunos ambientes)
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='analisis' AND column_name='external_organization_id') THEN
                ALTER TABLE analisis DROP COLUMN external_organization_id;
            END IF;
        END $$;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analisis', sa.Column('external_organization_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'analisis', type_='foreignkey')
    op.drop_column('analisis', 'client_id')
    # ### end Alembic commands ###
