"""empty message

Revision ID: ba4453385a9c
Revises: bd7123e6f29b
Create Date: 2025-05-07 02:42:29.578498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba4453385a9c'
down_revision: Union[str, None] = 'bd7123e6f29b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nivel_educativo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nivel_educativo_id'), 'nivel_educativo', ['id'], unique=False)
    op.create_table('candidatos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('birthday', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('nivel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nivel_id'], ['nivel_educativo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidatos_id'), 'candidatos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidatos_id'), table_name='candidatos')
    op.drop_table('candidatos')
    op.drop_index(op.f('ix_nivel_educativo_id'), table_name='nivel_educativo')
    op.drop_table('nivel_educativo')
    # ### end Alembic commands ###
