"""agregar tabla analisis

Revision ID: bd7123e6f29b
Revises: a8cabb0e3665
Create Date: 2025-05-01 03:36:47.940415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd7123e6f29b'
down_revision: Union[str, None] = 'a8cabb0e3665'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analisis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analisis_feedback'), 'analisis', ['feedback'], unique=False)
    op.create_index(op.f('ix_analisis_id'), 'analisis', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analisis_id'), table_name='analisis')
    op.drop_index(op.f('ix_analisis_feedback'), table_name='analisis')
    op.drop_table('analisis')
    # ### end Alembic commands ###
