"""Agregando columna name_company

Revision ID: c024499cd841
Revises: 0c71dbcfd224
Create Date: 2025-04-07 16:23:07.801416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c024499cd841'
down_revision: Union[str, None] = '0c71dbcfd224'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contactos', sa.Column('name_company', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contactos', 'name_company')
    # ### end Alembic commands ###
