"""Agregando columna name_company

Revision ID: da5ea9eaeadb
Revises: c024499cd841
Create Date: 2025-04-07 16:33:41.860981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da5ea9eaeadb'
down_revision: Union[str, None] = 'c024499cd841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contactos', sa.Column('name_company', sa.String(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contactos', 'name_company')
    # ### end Alembic commands ###
