"""agregar external user id

Revision ID: e01c1b70a87c
Revises: 75f324d14069
Create Date: 2025-05-10 03:40:09.684817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e01c1b70a87c'
down_revision: Union[str, None] = '75f324d14069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidatos', sa.Column('external_user_id', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'candidatos', ['external_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidatos', type_='unique')
    op.drop_column('candidatos', 'external_user_id')
    # ### end Alembic commands ###
