"""modificando la tabla clientes borrando unique true

Revision ID: e691149bc285
Revises: 5ed413ef7740
Create Date: 2025-09-05 02:53:33.827781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e691149bc285'
down_revision: Union[str, None] = '5ed413ef7740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('clientes_external_organization_id_key', 'clientes', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('clientes_external_organization_id_key', 'clientes', ['external_organization_id'])
    # ### end Alembic commands ###
