"""Initial migration

Revision ID: f4719f18a3b6
Revises: 
Create Date: 2025-02-24 20:29:25.429164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4719f18a3b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_index(op.f('ix_clientes_name'), 'clientes', ['name'], unique=True)
    op.create_table('tipos_de_trabajo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_de_trabajo_id'), 'tipos_de_trabajo', ['id'], unique=False)
    op.create_index(op.f('ix_tipos_de_trabajo_title'), 'tipos_de_trabajo', ['title'], unique=False)
    op.create_table('funciones_del_trabajo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['tipos_de_trabajo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funciones_del_trabajo_id'), 'funciones_del_trabajo', ['id'], unique=False)
    op.create_index(op.f('ix_funciones_del_trabajo_title'), 'funciones_del_trabajo', ['title'], unique=False)
    op.create_table('habilidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['tipos_de_trabajo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habilidades_id'), 'habilidades', ['id'], unique=False)
    op.create_table('perfil_del_trabajador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['tipos_de_trabajo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perfil_del_trabajador_id'), 'perfil_del_trabajador', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_perfil_del_trabajador_id'), table_name='perfil_del_trabajador')
    op.drop_table('perfil_del_trabajador')
    op.drop_index(op.f('ix_habilidades_id'), table_name='habilidades')
    op.drop_table('habilidades')
    op.drop_index(op.f('ix_funciones_del_trabajo_title'), table_name='funciones_del_trabajo')
    op.drop_index(op.f('ix_funciones_del_trabajo_id'), table_name='funciones_del_trabajo')
    op.drop_table('funciones_del_trabajo')
    op.drop_index(op.f('ix_tipos_de_trabajo_title'), table_name='tipos_de_trabajo')
    op.drop_index(op.f('ix_tipos_de_trabajo_id'), table_name='tipos_de_trabajo')
    op.drop_table('tipos_de_trabajo')
    op.drop_index(op.f('ix_clientes_name'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
