"""add external_organization_id para analisis

Revision ID: faef773fb691
Revises: e691149bc285
Create Date: 2026-01-07 21:44:24.355849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faef773fb691'
down_revision: Union[str, None] = 'e691149bc285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analisis', sa.Column('external_organization_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analisis', 'external_organization_id')
    # ### end Alembic commands ###
